### ISSUE TITLE
how I can see the visualization of the ndt matching process?

### ISSUE THREAD

**Issue by JokerJohn** [rsasaki0109/ndt_mapping#1]
hi, rsasaki0109, thanks for your hard work! I'v learned a lot.
 i clone your code and mapping successfully in my rosbag , i can see the mapping process in rviz easysily when playing my rosbag .but when i run the ndt matching , how can i see the visualization in this way ? can you give a demo bag or pcd files? thanks a lot!

**Comment by rsasaki0109** [comment]
Sorry. I didn't notice your comment.
Please contact me if you need anything.
