### ISSUE TITLE
z轴漂移

### ISSUE THREAD

**Issue by LDX596999414** [rsasaki0109/ndt_mapping#2]
请问在建图的时候，你是否遇到了z轴偏移的情况，有解决嘛

**Comment by rsasaki0109** [comment]
This package does not specifically address z-direction drift.
You can suppress z-drift by removing noise from the input point clouds and by modifying the program so that the IMU's roll and pitch are set to the default values for scan matching.

**Comment by LDX596999414** [comment]
> This package does not specifically address z-direction drift.
> In ways other than parameter tuning, Z-drift can be suppressed by removing noise from the input point cloud and by modifying the program so that the IMU roll and pitch are set to the default values for scan matching.

I have set the IMU's roll and pitch to the scan matching defaults. But it doesn't seem to work.

**Comment by rsasaki0109** [comment]
A certain amount of z-direction drift cannot be avoided with current OSS mapping module by scan matching only, such as loam or ndt,gicp.

If you want to compensate for the distortions, I recommend you to use packages with loop closure.

LeGO-LOAM
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM

Cartographer ROS
https://github.com/cartographer-project/cartographer_ros

**Comment by LDX596999414** [comment]
> 当前的OSS映射模块无法通过仅扫描匹配（例如壤土或ndt，gicp）来避免一定量的z方向漂移。
> 
> 如果要补偿漂移，建议您使用带闭环的包装。
> 
> 乐高LOAM [https://github.com/RobustFieldAutonomyLab/](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM)乐高LOAM
> [](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM)
> 
> 制图师ROS
> https://github.com/cartographer-project/cartographer_ros

Okay, I got it .Thank you very much.

**Comment by LDX596999414** [comment]
> A certain amount of z-direction drift cannot be avoided with current OSS mapping modules by scan matching only, such as loam or ndt,gicp.
> 
> If you want to compensate for the drift, I recommend you to use packages with loop closure.
> 
> LeGO-LOAM
> https://github.com/RobustFieldAutonomyLab/LeGO-LOAM
> 
> Cartographer ROS
> https://github.com/cartographer-project/cartographer_ros
Okay, I got it
Thank you very much.

**Comment by LDX596999414** [comment]
> A certain amount of z-direction drift cannot be avoided with current OSS mapping modules by scan matching only, such as loam or ndt,gicp.
> 
> If you want to compensate for the drift, I recommend you to use packages with loop closure.
> 
> LeGO-LOAM
> https://github.com/RobustFieldAutonomyLab/LeGO-LOAM
> 
> Cartographer ROS
> https://github.com/cartographer-project/cartographer_ros


Okay, I got it
Thank you very much.
