### ISSUE TITLE
how to build it and get it running on ros noetic ?

### ISSUE THREAD

**Issue by khaledelmadawi** [rsasaki0109/ndt_mapping#3]
Hi, I cloned the repo and i am trying to build it on ros-noetic, but it fails and can't reach the root cause, can you give me a hand in such an issue?

**Comment by rsasaki0109** [comment]
I've never built this package on ros noetic.
If you tell me the details of the error, I might be able to help you

**Comment by git-chenjiqing** [comment]
fatal error: toolkits/point_cloud/MapManager.hpp: 没有那个文件或目录
 #include <toolkits/point_cloud/MapManager.hpp>
