### ISSUE TITLE
Where do toolkits come from

### ISSUE THREAD

**Issue by git-chenjiqing** [rsasaki0109/ndt_mapping#6]
Hello
Where do toolkits come from
The following error occurred when I compiled this project
```
fatal error: toolkits/point_cloud/MapManager.hpp: 
 #include <toolkits/point_cloud/MapManager.hpp>
```

**Comment by rsasaki0109** [comment]
@git-chenjiqing 
As you can see from the source code, there is no "#include <toolkits/point_cloud/MapManager.hpp>" description in ndt_mapping.
I think there is a problem in your environment.(For example, you may have changed the version of pcl.)

**Comment by git-chenjiqing** [comment]
https://github.com/PointCloudLibrary/pcl
Latest main branch

**Comment by git-chenjiqing** [comment]
https://github.com/PointCloudLibrary/pcl
Latest master branch

**Comment by git-chenjiqing** [comment]
about PCL
What version should I install？

**Comment by rsasaki0109** [comment]
@git-chenjiqing 
It depends on the version of ros.
It's probably a problem between ros and pcl, so you can use the pcl version that comes as standard when you install ros.

**Comment by git-chenjiqing** [comment]
Hello
My ROS version is melodic
I install PCL through source code compilation

**Comment by rsasaki0109** [comment]
I think you can uninstall that compiled pcl.
If that doesn't work, try using the following command.

rosdep install -i --from-paths <PATH-TO-NDT_MAPPING-PACKAGE>

If that doesn't work, you may need to reinstall ros or ubuntu.

**Comment by git-chenjiqing** [comment]
I found two versions of PCL installed, 1.8 and 1.12. Now I have uninstalled them all
Execute this command
```
rosdep install -i --from-paths ndt_mapping-master
#All required rosdeps installed successfully
```

**Comment by git-chenjiqing** [comment]
When I completely uninstall PCL, compile it
```
/home/chenjiqing/kaijia_ws/src/ndt_mapping-master/include/ndt_mapping.h:38:10: fatal error: pcl/io/io.h: 没有那个文件或目录
 #include <pcl/io/io.h>
          ^~~~~~~~~~~~~
In file included from /home/chenjiqing/kaijia_ws/src/ndt_mapping-master/src/ndt_mapping.cpp:23:0:
/home/chenjiqing/kaijia_ws/src/ndt_mapping-master/include/ndt_mapping.h:38:10: fatal error: pcl/io/io.h: 没有那个文件或目录
 #include <pcl/io/io.h>
          ^~~~~~~~~~~~~
/home/chenjiqing/kaijia_ws/src/ndt_mapping-master/src/ndt_mapping_submaps.cpp:39:10: fatal error: pcl/io/io.h: 没有那个文件或目录
 #include <pcl/io/io.h>
```
Then I followed the dependency instructions as follows
```
sudo apt-get install ros-melodic-pcl-*
```
**It seems better now**
**Thank you for your continuous reply**

**Comment by git-chenjiqing** [comment]
Hello, there's another question

How do I convert occupancymap to pointcloud2

**Comment by rsasaki0109** [comment]
@git-chenjiqing I've never done it before, so I'm not sure.

**Comment by rsasaki0109** [comment]
The issue in the title is resolved, so close this issue.
